all_animals = [
    {
        "category": "Bat",
        "shortDescription": "Bats are the only mammals capable of sustained flight, with wings that are more akin to a thin membrane stretched between elongated fingers. They inhabit the night sky, using echolocation to navigate and find their prey. Often shrouded in myth and mystery, bats play a vital role in ecosystems as pollinators and natural pest controllers. Their nocturnal lifestyle and distinctive appearance make them intriguing and vital creatures of the night.",
        "habitat": "Woodland and caves",
        "diet": "Omnivore",
        "location": "Africa, Asia, Central-America, Eurasia, Europe, North-America, Oceania, South-America",
        "type": "Mammal",
        "lifeSpan": "10 - 30 years",
        "weight": "2g - 1,000g",
        "top_speed": "25 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Bat.jpg"
    },
    {
        "category": "Bear",
        "shortDescription": "Bears are large, powerful mammals known for their thick fur, strong limbs, and often gentle yet formidable presence. Found across various continents, they range from the polar bears of the Arctic, masters of icy domains, to the pandas munching bamboo in Chinas forests. Despite their often solitary nature, bears inspire a blend of admiration and caution, symbolizing strength and wilderness in many cultures.",
        "habitat": "Forest and mountainous regions",
        "diet": "Omnivore",
        "location": "Asia, Central-America, Eurasia, Europe, North-America, South-America",
        "type": "Mammal",
        "lifeSpan": "15 - 35 years",
        "weight": "27kg - 450kg",
        "top_speed": "35 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Bear.png"
    },
    {
        "category": "Bee",
        "shortDescription": "Bees are small, winged insects vital for pollination. Known for their striped bodies, they live in colonies, produce honey, and play a crucial role in sustaining ecosystems and agriculture.",
        "habitat": "Any habitat where there are flowering plants",
        "diet": "Omnivore",
        "location": "Africa, Asia, Central-America, Eurasia, Europe, North-America, Oceiania, South-America",
        "type": "Insect",
        "lifeSpan": "15 - 38 days",
        "weight": "115g - 128g",
        "top_speed": "20 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Bee.png"
    },
    {
        "category": "Butterfly",
        "shortDescription": "Butterflies are delicate, winged insects known for their vibrant patterns and transformative life cycle. Theyre pollinators and a symbol of change and beauty in many cultures.",
        "habitat": "Quiet forests and pastures",
        "diet": "Herbivore",
        "location": "Africa, Asia, Central-America, Eurasia, Europe, North-America, Ocean, Oceania, South-America",
        "type": "Insect",
        "lifeSpan": "2 - 4 weeks",
        "weight": "2g - 3g",
        "top_speed": "10 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Butterfly.png"
    },
    {
        "category": "Cat",
        "shortDescription": "Cats are small, carnivorous mammals known for their agile bodies, sharp retractable claws, and distinctive purring. Theyre often kept as pets for their affectionate nature and hunting prowess, and have been revered or adored in various cultures throughout history.",
        "habitat": "Savannah, Open forest, Scrubland, Swamp, and farmland",
        "diet": "Carnivore",
        "location": "Africa, Asia, Central-America, Eurasia, Europe, North-America, Ocean, Oceania, South-America",
        "type": "Mammal",
        "lifeSpan": "12 - 18 years",
        "weight": "4kg - 5kg",
        "top_speed": "33 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Cat.png"
    },
    {
        "category": "Chicken",
        "shortDescription": "Chickens are average-sized fowls, characterized by smaller heads, short beaks and wings, and a round body perched on featherless legs",
        "habitat": "Any habitat where there is vegetation",
        "diet": "Herbivore",
        "location": "Africa, Asia, Central-America, Eurasia, Europe, North-America, Oceania, South-America",
        "type": "Bird",
        "lifeSpan": "5 - 10 years",
        "weight": "4kg",
        "top_speed": "16 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Chicken.png"
    },
    {
        "category": "Chimpanzee",
        "shortDescription": "Chimpanzees are highly intelligent primates native to African forests and savannahs. Theyre our closest living relatives, sharing about 98% of our DNA, and are known for their complex social structures, use of tools, and expressive behaviors.",
        "habitat": "Tropical forest and woody savanna",
        "diet": "Omnivore",
        "location": "Africa",
        "type": "Mammal",
        "lifeSpan": "50 - 60 years",
        "weight": "26kg - 70kg",
        "top_speed": "25 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Chimpanzee.png"
    },
    {
        "category": "Cow",
        "shortDescription": "Cows are large, herbivorous mammals domesticated for their milk, meat, and leather. Theyre ruminants with a gentle demeanor, often seen grazing in pastures, and hold significant cultural and economic importance in many societies.",
        "habitat": "Forest and grassland",
        "diet": "Herbivore",
        "location": "Africa, Asia, Central-America, Eurasia, Europe, North-America, Oceania, South-America",
        "type": "Mammal",
        "lifeSpan": "12 - 20 years",
        "weight": "400kg - 800kg",
        "top_speed": "20 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Cow.png"
    },
    {
        "category": "Deer",
        "shortDescription": "Deer are graceful herbivores with slender bodies and typically sport branched antlers. Theyre found in various habitats worldwide, from forests to grasslands, and are known for their cautious demeanor and swift movements.",
        "habitat": "Dense forest and planted areas",
        "diet": "Herbivore",
        "location": "Asia, Eurasia, Europe, North-America",
        "type": "Mammal",
        "lifeSpan": "10 - 20 years",
        "weight": "10kg - 450kg",
        "top_speed": "43 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Deer.png"
    },
    {
        "category": "Dog",
        "shortDescription": "Dogs are domesticated canines known for their loyalty and diverse breeds. Theyre cherished companions in many cultures, serving roles from family pets to working animals, and are celebrated for their unwavering bond with humans.",
        "habitat": "Forests and brush lands",
        "diet": "Omnivore",
        "location": "Africa, Asia, Eurasia, Europe, South-America, Oceania, North-America",
        "type": "Mammal",
        "lifeSpan": "10 - 13 years",
        "weight": "1.4kg - 110kg",
        "top_speed": "31 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Dog.png"
    },
    {
        "category": "Dolphin",
        "shortDescription": "Dolphins are intelligent marine mammals known for their playful behavior and complex vocalizations. Theyre social creatures, often traveling in pods, and display empathy and cooperation, captivating many with their grace and agility in the water.",
        "habitat": "All of the worlds oceans, rivers in Asia and South America",
        "diet": "Carnivore",
        "location": "Ocean",
        "type": "Mammal",
        "lifeSpan": "20 - 45 years",
        "weight": "100kg - 300 kg",
        "top_speed": "25 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Dolphin.png"
    },
    {
        "category": "Donkey",
        "shortDescription": "Donkeys are sturdy, domesticated animals known for their patience and endurance. Theyre often used as working animals, especially in rough terrains, valued for their dependable nature and ability to carry heavy loads over long distances.",
        "habitat": "Arid forests and deserts",
        "diet": "Herbivore",
        "location": "Africa, Asia, Central-America, Eurasia, Europe, North-America, Oceania, South-America",
        "type": "Mammal",
        "lifeSpan": "15 - 30 years",
        "weight": "200kg - 258kg",
        "top_speed": "15 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Donkey.png"
    },
    {
        "category": "Duck",
        "shortDescription": "Ducks are waterfowl with broad bills, webbed feet, and a waddling gait. Theyre found in both freshwater and saltwater habitats and are known for their quacking sounds. Often seen floating on water or in flight, ducks are valued for their meat, eggs, and ornamental appeal.",
        "habitat": "Rivers, lakes and woodland wetlands",
        "diet": "Omnivore",
        "location": "Africa, Asia, Central-America, Eurasia, Europe, North-America, Ocean, Oceania, South-America",
        "type": "Bird",
        "lifeSpan": "4 - 8 years",
        "weight": "0.7kg - 1.4kg",
        "top_speed": "60 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Duck.png"
    },
    {
        "category": "Eagle",
        "shortDescription": "Eagles are large, powerful birds of prey with sharp talons and keen eyesight. Theyre known for their majestic flight and striking appearance, often symbolizing freedom and strength. Found globally, eagles are revered in many cultures and play crucial roles in their ecosystems as apex predators.",
        "habitat": "Northern tundra to tropical rainforests and deserts",
        "diet": "Carnivores",
        "location": "North-America",
        "type": "Bird",
        "lifeSpan": "15 years",
        "weight": "5kg",
        "top_speed": "42 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Eagle.png"
    },
    {
        "category": "Elephant",
        "shortDescription": "Elephants are massive, herbivorous mammals recognized for their long trunks and impressive tusks. Theyre highly intelligent and social, living in matriarchal groups and displaying intricate behaviors. Native to Africa and Asia, elephants hold cultural significance in many societies and are both revered and, sadly, targeted for their ivory.",
        "habitat": "wetlands, forest, grassland, savanna and desert",
        "diet": "Herboviore",
        "location": "Africa, Asia",
        "type": "Mammal",
        "lifeSpan": "65 years",
        "weight": "1,800kg - 6,300kg",
        "top_speed": "24 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Elephant.png"
    },
    {
        "category": "Fox",
        "shortDescription": "Foxes are small to medium-sized carnivores with a bushy tail and sharp features. They are adaptable and can be found in various habitats, from forests to urban areas. Known for their cunning and agility, foxes are often featured in folklore and legends as clever and resourceful creatures.",
        "habitat": "Gardens, rivers and wetland, woodland, and arable land",
        "diet": "Omnivore",
        "location": "Eurasia, Europe, North-America",
        "type": "Mammal",
        "lifeSpan": "2 - 3 years",
        "weight": "3.5kg - 7kg",
        "top_speed": "31 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Fox.png"
    },
    {
        "category": "Goat",
        "shortDescription": "Goats are domesticated ruminants with a keen ability to graze on various terrains. They are versatile animals, kept for their milk, meat, and wool, and are often found on farms and in mountainous regions. Known for their curious nature and distinct bleats, goats have been beneficial companions to humans for thousands of years.",
        "habitat": "Rocky or hilly country in the semi-arid rangelands",
        "diet": "Herbivore",
        "location": "Asia, Europe, North-America",
        "type": "Mammal",
        "lifeSpan": "8 - 12 years",
        "weight": "20kg - 140kg",
        "top_speed": "9 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Goat.png"
    },
    {
        "category": "Gorilla",
        "shortDescription": "Large primates native to African forests, recognized for their intelligence and strong family bonds. They are primarily herbivores and are divided into mountain and lowland species. Gorillas are endangered, facing threats from habitat loss and poaching.",
        "habitat": "Tropical forest and jungles in mountainous regions",
        "diet": "Omnivore",
        "location": "Africa",
        "type": "Mammal",
        "lifeSpan": "35 - 50 years",
        "weight": "204kg - 227kg",
        "top_speed": "25 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Gorilla.png"
    },
    {
        "category": "Hedgehog",
        "shortDescription": "Small, nocturnal mammals covered in spiky quills. When threatened, they roll into a ball for protection. Known for their curious nature, some species are kept as pets, while others remain wild, often seen in gardens and woodlands.",
        "habitat": "Dense vegetation and woodland",
        "diet": "Omnivore",
        "location": "Africa, Asia, Eurasia, Europe",
        "type": "Mammal",
        "lifeSpan": "3 - 6 years",
        "weight": "1 - 2kg",
        "top_speed": "25 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Hedgehog.png"
    },
    {
        "category": "Hippopotamus",
        "shortDescription": "Large, semi-aquatic mammals native to Africa, known for their barrel-shaped bodies and large jaws. They spend much of their time in water to keep cool and emerge at dusk to graze. Despite their bulk, they are agile swimmers and runners.",
        "habitat": "Lakes, rivers and wetlands",
        "diet": "Herbivore",
        "location": "Africa",
        "type": "Mammal",
        "lifeSpan": "30 - 40 years",
        "weight": "160kg - 270kg",
        "top_speed": "18.6 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Hippo.png"
    },
    {
        "category": "Horse",
        "shortDescription": "Powerful and graceful animals, domesticated for thousands of years for work, transport, and recreation. Known for their speed, endurance, and bond with humans, horses have played crucial roles in history and are celebrated in many cultures.",
        "habitat": "Rainforests, woodlands and savannas",
        "diet": "Omnivore",
        "location": "Africa, Asia, Oceania",
        "type": "Bird",
        "lifeSpan": "40 years",
        "weight": "6.17 kg",
        "top_speed": "18.6 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Horse.png"
    },
    {
        "category": "Hummingbird",
        "shortDescription": "Tiny, iridescent birds known for their rapid wing beats and hovering flight. They feed on nectar, using their long, specialized beaks, and play a key role in pollination. Found primarily in the Americas, their vibrant colors and agility make them a favorite among birdwatchers.",
        "habitat": "Farms and open fields",
        "diet": "Herbivore",
        "location": "North-America",
        "type": "Mammal",
        "lifeSpan": "25 – 30 years",
        "weight": "600 – 900 kg",
        "top_speed": "50 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/HummingBird.png"
    },
    {
        "category": "Kangaroo",
        "shortDescription": "Native Australian marsupials known for their powerful hind legs and hopping locomotion. They carry their young in a front pouch and are recognized worldwide as a symbol of Australia. Kangaroos live in diverse habitats, from forests to grassy plains.",
        "habitat": "All oceans on planet earth",
        "diet": "Carnivore",
        "location": "Ocean",
        "type": "Cnidaria",
        "lifeSpan": "3 - 6 months",
        "weight": "20 - 400g",
        "top_speed": "5 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Kangaroo.png"
    },
    {
        "category": "Koala",
        "shortDescription": "Tree-dwelling marsupial native to Australia, recognized for its teddy bear-like appearance. It feeds primarily on eucalyptus leaves and is known for its slow metabolism and prolonged sleeping habits. Despite their cuddly appearance, they have strong claws for climbing.",
        "habitat": "Dry forests, desert and grassland",
        "diet": "Omnivore",
        "location": "Oceania",
        "type": "Mammal",
        "lifeSpan": "4 - 10 years",
        "weight": "18 - 95kg",
        "top_speed": "35 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Koala.png"
    },
    {
        "category": "Leopard",
        "shortDescription": "Agile big cats with distinctive golden-yellow coats covered in rosette-shaped spots. They are stealthy hunters found in various habitats across Africa and Asia, known for their strength, speed, and elusive nature.",
        "habitat": "Deserts and semi-desert regions of southern Africa, to arid regions of North Africa",
        "diet": "Carnivore",
        "location": "Africa",
        "type": "Mammal",
        "lifeSpan": "10 - 15 years",
        "weight": "25kg - 48kg",
        "top_speed": "40 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Leopard.png"
    },
    {
        "category": "Lion",
        "shortDescription": "Majestic big cats known for their regal appearance and powerful roars. They are often referred to as the \"King of the Jungle\" and are found primarily in Africa. Lions live in social groups called prides and are renowned for their strength, teamwork, and role as apex predators.",
        "habitat": "Open woodland, scrub, grassland",
        "diet": "Carnivore",
        "location": "Africa, Asia",
        "type": "Mammal",
        "lifeSpan": "8 - 15 years",
        "weight": "120kg - 249kg",
        "top_speed": "35 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Lion.png"
    },
    {
        "category": "Octopus",
        "shortDescription": "Intelligent, ocean-dwelling cephalopods with soft, bulbous bodies and long, flexible tentacles. They are masters of camouflage and have complex behaviors, including problem-solving abilities. Octopuses are known for their exceptional hunting skills and are considered culinary delicacies in many cuisines.",
        "habitat": "Tropical and temperate waters worldwide",
        "diet": "Omnivore",
        "location": "Ocean",
        "type": "Mollusca",
        "lifeSpan": "2 - 15 years",
        "weight": "5 - 75kg",
        "top_speed": "27 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Octopus.png"
    },
    {
        "category": "Owl",
        "shortDescription": "Nocturnal birds of prey with keen night vision and silent flight. They have distinctive large, round faces, sharp talons, and are known for their wisdom in folklore. Owls come in various species and sizes, inhabiting diverse ecosystems around the world.",
        "habitat": "Lowland and coniferous forests",
        "diet": "Carnivore",
        "location": "Central-America, North-American, South-America",
        "type": "Bird",
        "lifeSpan": "4 years",
        "weight": "2 kg",
        "top_speed": "20 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Owl.jpg"
    },
    {
        "category": "Panda",
        "shortDescription": "Iconic black and white bears native to China, known for their bamboo-based diet and distinctive appearance. They are symbols of conservation efforts and are highly endangered due to habitat loss and poaching.",
        "habitat": "High-altitude, moist bamboo forest",
        "diet": "Omnivore",
        "location": "Asia",
        "type": "Mammal",
        "lifeSpan": "20 - 35 years",
        "weight": "110kg - 250kg",
        "top_speed": "20 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Panda.png"
    },
    {
        "category": "Parrot",
        "shortDescription": "Colorful, intelligent birds with the ability to mimic sounds and human speech. They are found in tropical and subtropical regions worldwide and are popular as pets due to their sociable nature and striking plumage.",
        "habitat": "Rainforests, grasslands, savannas, semi-arid regions, and even islands",
        "diet": "Herbivore",
        "location": "Asia, Africa, Europe, North-America, Oceania",
        "type": "Bird",
        "lifeSpan": "23 years",
        "weight": "0.5kg -1kg",
        "top_speed": "42 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Parrot.png"
    },
    {
        "category": "Penguin",
        "shortDescription": "Flightless, aquatic birds native to the Southern Hemisphere, known for their tuxedo-like plumage and strong swimming abilities. They live in colonies and are exceptional hunters in the ocean, with species ranging from the Emperor penguin to the Little Blue penguin.",
        "habitat": "pelagic to coastal to inland freshwater environments",
        "diet": "Carnivore",
        "location": "Antartica, Ocean, Oceania, South-America",
        "type": "Bird",
        "lifeSpan": "15 - 20 years",
        "weight": "3.2 - 6.4kg",
        "top_speed": "22 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Penguin.png"
    },
    {
        "category": "Pig",
        "shortDescription": "Domesticated mammals known for their intelligence and diverse breeds. They are raised for meat production, but also kept as pets. Pigs are highly adaptable animals, found in various agricultural settings worldwide.",
        "habitat": "Forests and grassland",
        "diet": "Carnivore",
        "location": "Asia, Eurasia, Europe, North-America",
        "type": "Mammal",
        "lifeSpan": "8 - 15 years",
        "weight": "30 - 350kg",
        "top_speed": "11 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Pig.png"
    },
    {
        "category": "Pigeon",
        "shortDescription": "Small to medium-sized birds often found in urban environments. They have a distinctive cooing call and are known for their ability to navigate and find their way home over long distances. Pigeons are also symbols of peace and have been used as messengers throughout history.",
        "habitat": "Often found in towns and cities, as well as farmlands, fields, and rocky cliffs",
        "diet": "Omnivore",
        "location": "Asia, Africa, Central-America, Eurasia, Europe, North-America, Oceania, South-America",
        "type": "Bird",
        "lifeSpan": "6 years",
        "weight": "0.3kg - 0.5kg",
        "top_speed": "55 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Pigeon.png"
    },
    {
        "category": "Rhinoceros",
        "shortDescription": "Large herbivorous mammals known for their thick skin and one or more horn-like structures on their noses. Rhinos are found in Africa and Asia and are endangered due to poaching for their horns, which are falsely believed to have medicinal properties. They play vital roles in their ecosystems as grazers and browsers.",
        "habitat": "Tropical bushland, grassland and savannas",
        "diet": "Herbivore",
        "location": "Africa, Asia",
        "type": "Mammal",
        "lifeSpan": "35 - 50 years",
        "weight": "300 - 500kg",
        "top_speed": "30 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Rhino.png"
    },
    {
        "category": "Seahorse",
        "shortDescription": "Unique, marine fish with horse-like heads and curled tails. They are slow swimmers and are often found clinging to seagrasses or coral. Seahorses are known for their distinctive appearance and are popular in marine aquariums.",
        "habitat": "Shallow tropical waters and coral reefs",
        "diet": "Omnivore",
        "location": "Africa, Asia, Central-America, Eurasia, Europe, North-America, Ocean, Oceania, South-America",
        "type": "Fish",
        "lifeSpan": "2 - 6 years",
        "weight": "0.1kg - 00.5g",
        "top_speed": "1 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Seahorse.png"
    },
    {
        "category": "Seal",
        "shortDescription": "Aquatic mammals characterized by their sleek bodies, flippers, and ability to live both in the water and on land. Seals are found in various cold-water regions around the world and are known for their playful behavior and hunting skills.",
        "habitat": "Coastal waters and rocky shores",
        "diet": "Carnivore",
        "location": "Ocean",
        "type": "Mammal",
        "lifeSpan": "15 - 25 years",
        "weight": "105kg - 3,000kg",
        "top_speed": "27 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Seal.png"
    },
    {
        "category": "Shark",
        "shortDescription": "Predatory fish with cartilaginous skeletons and sharp teeth. They are apex predators in marine ecosystems and come in various species, from the enormous whale shark to the fearsome great white shark. Sharks are essential for maintaining the balance of ocean life.",
        "habitat": "Oceans worldwide, from shallow coastal waters to deep sea environments",
        "diet": "Carnivore",
        "location": "Ocean",
        "type": "Mammal",
        "lifeSpan": "20 - 30 years",
        "weight": "680kg - 1814kg",
        "top_speed": "60 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Shark.png"
    },
    {
        "category": "Sheep",
        "shortDescription": "Domesticated ruminant mammals known for their woolly coats and herding behavior. They are raised for their meat, wool, and milk, and are found in farming communities worldwide. Sheep are valued for their versatility and have been an essential part of human agriculture for thousands of years.",
        "habitat": "Grass plains and mountainous regions",
        "diet": "Herbivore",
        "location": "Africa, Asia, Central-America, Eurasia, North-America, Oceania, South-America",
        "type": "Mammal",
        "lifeSpan": "5 - 10 years",
        "weight": "40kg - 130kg",
        "top_speed": "25 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Sheep.png"
    },
    {
        "category": "Snake",
        "shortDescription": "Legless reptiles with elongated bodies and forked tongues. They come in various species, from non-venomous garden snakes to deadly vipers. Snakes are found on every continent except Antarctica and play vital roles in ecosystems as both predators and prey.",
        "habitat": "Grass plains and mountainous regions",
        "diet": "Herbivore",
        "location": "Africa, Asia, Central-America, Eurasia, Europe, North-America, Oceania, South-America",
        "type": "Reptile",
        "lifeSpan": "30 years",
        "weight": "0.1 - 250 kg",
        "top_speed": "12 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Snake.png"
    },
    {
        "category": "Squirrel",
        "shortDescription": "Small to medium-sized rodents known for their bushy tails and acrobatic tree-climbing abilities. They are found in various habitats, including urban areas, and are known for their hoarding behavior of nuts and seeds for winter. Squirrels are agile and playful creatures often seen in parks and woodlands.",
        "habitat": "Woodland and dense forests",
        "diet": "Omnivore",
        "location": "Africa, Asia, Central-America, Euraisa, Europe, North-America, South-America",
        "type": "Mammal",
        "lifeSpan": "2 - 8 years",
        "weight": "0.25kg - 1kg",
        "top_speed": "16 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Squirrel.png"
    },
    {
        "category": "Starfish",
        "shortDescription": "Marine invertebrates with radial symmetry and typically five arms (though some species have more). They are found in oceans around the world and are known for their regenerative abilities, vibrant colors, and distinctive appearance. Starfish play important roles in marine ecosystems.",
        "habitat": "Coral reef",
        "diet": "Carnivore",
        "location": "Ocean",
        "type": "Asteroidea",
        "lifeSpan": "35 years",
        "weight": "0.1kg - 6kg",
        "top_speed": "0.6 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Starfish.png"
    },
    {
        "category": "Tiger",
        "shortDescription": "Large, powerful big cats with distinctive orange coats and black stripes. They are apex predators found primarily in Asia and are known for their strength, stealth, and solitary nature. Tigers are endangered due to habitat loss and poaching for their body parts.",
        "habitat": "Dense tropical forest",
        "diet": "Carnivore",
        "location": "Africa, Eurasia",
        "type": "Mammal",
        "lifeSpan": "18 - 25 years",
        "weight": "267kg - 300kg",
        "top_speed": "60 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Tiger.png"
    },
    {
        "category": "Turkey",
        "shortDescription": "Large birds native to North America, recognized for their distinctive fan-shaped tails and wattled necks. They are known for their role in the Thanksgiving holiday feast and are raised for their meat. Turkeys are agile runners and are also found in the wild in forested areas.",
        "habitat": "Forest, shrubland and grassy plains",
        "diet": "Omnivore",
        "location": "Central-America, North-America",
        "type": "Bird",
        "lifeSpan": "1 - 10 years",
        "weight": "3kg - 11kg",
        "top_speed": "6 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Turkey.png"
    },
    {
        "category": "Turtle",
        "shortDescription": "Shelled reptiles known for their slow, methodical movements and protective shells. They come in various species, inhabiting both terrestrial and aquatic environments. Turtles are celebrated for their longevity and are often associated with wisdom and endurance.",
        "habitat": "Aquatic, muddy, swampy areas, dry land for sun basking",
        "diet": "Omnivore",
        "location": "Africa, Asia, Central-America, Eurasia, Europe, North-America, Ocean, Oceania, South-America",
        "type": "Reptile",
        "lifeSpan": "50 - 100 years",
        "weight": "250kg - 907 kg",
        "top_speed": "3 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Turtle.png"
    },
    {
        "category": "Whale",
        "shortDescription": "Enormous marine mammals known for their size and aquatic lifestyles. They are divided into toothed and baleen whale species and are found in oceans worldwide. Whales are celebrated for their majestic presence and vocalizations, including the haunting songs of humpback whales.",
        "habitat": "Warm coastal waters and open ocean",
        "diet": "Carnivore",
        "location": "Ocean",
        "type": "Fish",
        "lifeSpan": "60 - 70 years",
        "weight": "60 - 1,200kg",
        "top_speed": "10 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Whale.png"
    },
    {
        "category": "Wolf",
        "shortDescription": "Carnivorous mammals known for their pack behavior and distinct howling vocalizations. They are found in various species and habitats around the world, from forests to tundra. Wolves play critical roles in ecosystems as apex predators and are symbols of wilderness and resilience.",
        "habitat": "Grass plains and woodland",
        "diet": "Carnivore",
        "location": "Africa, Asia, Central-America, Euraisa, Europe, North-America, South-America",
        "type": "Mammal",
        "lifeSpan": "10 - 12 years",
        "weight": "36 - 68 kg",
        "top_speed": "46 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Wolf.png"
    },
    {
        "category": "Wombat",
        "shortDescription": "Small, burrowing marsupials native to Australia. They have sturdy builds, short legs, and a unique backward-facing pouch. Wombats are known for their nocturnal habits and are herbivorous, primarily feeding on grasses and roots",
        "habitat": "Woodland and coastal shrub land",
        "diet": "Herbivore",
        "location": "Oceania",
        "type": "Mammal",
        "lifeSpan": "20 - 26 years",
        "weight": "20 - 35kg",
        "top_speed": "25 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Wombat.jpg"
    },
    {
        "category": "Zebra",
        "shortDescription": "Striped, herbivorous mammals native to Africa, known for their distinctive black and white stripes. Zebras are social animals often found in groups and are recognizable symbols of the African savannah. Their stripes are believed to serve as a form of camouflage and a way to deter biting insects.",
        "habitat": "Open grassland and plains",
        "diet": "Herbivore",
        "location": "Africa",
        "type": "Mammal",
        "lifeSpan": "20 - 30 years",
        "weight": "220kg - 405kg",
        "top_speed": "40 mph",
        "image": "https://bookstoredemo.blob.core.windows.net/animals/Zebra.png"
    }
]